#!/bin/bash

release_file=/etc/os-release
logfile=/var/log/updater.log
errorlog=/var/log/updater_errors.log

if grep -q "Arch" $release_file
  then
#The host is based on Arch, run the pacman update command
    sudo pacman -Syu 1>>$logfile 2>>$errorlog
    if [ $? -ne 0]
#is the exitcode not equal to 0?
      echo "an error occured, please check the $errorlog.file."
	then 
	fi
fi
if grep -q "Pop" $release_file || grep -q "Ubuntu" $release_file
then
	#the host is based on Ubuntu,
	#Run the apt version of the command
	sudo apt update 1>>$logfile 2>>$errorlog
	sudo apt dist-update -y 1>>$logfile 2>>$errorlog
	if [$? -ne 0]
	then
		echo "An error occurred, please check the $errorlog file"
	fi
fi
